### PR TITLE
Fix seekers using excess memories by holding onto digest readers after call to Open()

### LINKED ISSUE #476: Make seeker's not hang onto FDDigestReaders
Currently every seeker that we open holds onto about 5 FDDigestReaders. Even when we close/reset them, the underlying buffered reader is not de-allocated.

In our short-lived production workloads this doesn't matter at all, but in clusters with a large number of namespaces/shards/blocks (hundreds of thousands) this adds up to 10's of gigabytes of wasted memory 65KiB size per digest reader)

We should make sure that the buffered readers are properly de-allocated when they are no longer needed.

### PR DESCRIPTION
**Pull request by richardartoul**
Fixes #476

### CODE REVIEW

File: src/dbnode/persist/fs/seek.go [hunk 1]
```diff
@@ -195,26 +177,34 @@ func (s *seeker) Open(namespace ident.ID, shard uint32, blockStart time.Time) er
...
+		digestFdWithDigestContents = digest.NewFdWithDigestContentsReader(s.opts.infoBufferSize)
+	)
 	defer func() {
-		// NB(r): We don't need to keep these FDs open as we use these up front
-		s.infoFdWithDigest.Close()
-		s.indexFdWithDigest.Close()
-		s.bloomFilterFdWithDigest.Close()
-		s.digestFdWithDigestContents.Close()
+		// NB(rartoul): We don't need to keep these FDs open as we use these up front
+		infoFdWithDigest.Close()
```
Comment (prateek) [inline src/dbnode/persist/fs/seek.go]: Looks like this closes the underlying fd too. Is the `mmap` valid after the fd is closed?

Comment (richardartoul) [reply src/dbnode/persist/fs/seek.go]: Yeah its safe to close an FD once the mmap syscall has executed, it wont affect the mmap (this is what we were already doing also)

Comment (prateek) [reply src/dbnode/persist/fs/seek.go]: 👍 sounds good
