### PR TITLE
Fix broken test

### LINKED ISSUE #389: Fix broken test TestDeleteInactiveFiles

### PR DESCRIPTION
**Pull request by richardartoul**
Closes #389

### CODE REVIEW

File: persist/fs/files_test.go [hunk 1]
```diff
@@ -165,27 +165,29 @@ func TestDeleteFiles(t *testing.T) {
 }
 
 func TestDeleteInactiveFiles(t *testing.T) {
-	tempPrefix := "temp/"
+	tempPrefix, err := ioutil.TempDir("", "foo")
+	require.NoError(t, err)
+	defer func() {
```
Comment (katezaps) [inline persist/fs/files_test.go]: so is this the trick to getting it to eval later?

Comment (robskillington) [reply persist/fs/files_test.go]: `temp` would've only been available if you made it on your own machine, `ioutil.TempDir(...)` creates a temporary directory for use in a directory the stdlib manages.
